site_name: Openinfrastructure Lab
theme: 
  name: material
  features:
    - navigation.sections
    - navigation.instance
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Go to the dark side
      primary: red
      accent: pink
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Light side
      primary: red
      accent: pink

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  

copyright: Copyright &copy; 2023 Red Hat NA-SSA Team
